/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testEmptyArray()
     {
         String []array=new String[0] ;
         assertNull(App.encryption(array,"hello", 2,1));

     }
     @Test
     public void testfoundAndnotReverse()
     {
         String [] arr={"hello","world","this is","my","project"};
         assertEquals("ifmmp",App.encryption(arr,"hello", 1, 0));

     }
     @Test
     public void testfoundAndReverse()
     {
        String [] arr={"hello","world","this is","my","project"};
        assertEquals("pmmfi",App.encryption(arr,"hello", 1, 1));
     }
  
   
    
}
